# Generated by Django 3.2.5 on 2021-08-16 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
